services:
  - type: web
    name: instagram-post-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_interface:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 